[package]
name = "raidillon_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
glium  = { version = "0.35.0", features = ["glutin_backend", "simple_window_builder"] }
imgui = "0.12"
imgui-winit-support = "0.13"
imgui-glium-renderer = "0.13"
winit = "0.30"
